demotask7/gadgetsproject/gadgetsapp/urls.py
from django.urls import path
from .import views

app_name = 'gadgetsapp'
urlpatterns=[
    path('',views.index,name='index'),
    path('detail/<int:idnumber>/',views.detail,name='detail'),
    path('add/',views.addgadgets,name='addgadgets'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

demotask7/gadgetsproject/gadgetsproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gadgetsapp.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

demotask7/gadgetsproject/gadgetsapp/models.py
from django.db import models

# Create your models here.
class Gadgets(models.Model):
    title=models.CharField(max_length=250)
    desc=models.TextField()
    price=models.IntegerField()
    image=models.ImageField(upload_to='pics')

    def __str__(self):
        return self.title

demotask7/gadgetsproject/gadgetsapp/forms.py
from django import forms
from .models import Gadgets
class GadgetsForm(forms.ModelForm):
    class Meta:
        model=Gadgets
        fields=['title','desc','price','image']

demotask7/gadgetsproject/gadgetsapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
from .models import Gadgets
from .forms import GadgetsForm

def index(request):
    gadgets=Gadgets.objects.all()

    return render(request,"index.html",{'key1':gadgets})
def detail(request,idnumber):
    gadgets1=Gadgets.objects.get(id=idnumber)
    return render(request,"detail.html",{'gadgets':gadgets1})
def addgadgets(request):
    if request.method=="POST":
        name=request.POST.get('title')
        desc1=request.POST.get('desc')
        price1=request.POST.get('price')
        img=request.FILES['image']
        gadgets1=Gadgets(title=name,desc=desc1,price=price1,image=img)
        gadgets1.save()
        return redirect('/')
    return render(request,"add.html")
def update(request,id):
    gadgets=Gadgets.objects.get(id=id)
    form1=GadgetsForm(request.POST or None,request.FILES,instance=gadgets)
    if form1.is_valid():
        form1.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form1,'gadgets':gadgets})
def delete(request,id):
    if request.method=="POST":
        gadgets=Gadgets.objects.get(id=id)
        gadgets.delete()
        return redirect('/')
    return render(request,"delete.html")

demotask7/gadgetsproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="title" placeholder="Enter the Gadget Name">
  <input type="text" name="desc" placeholder="Enter the description">
  <input type="number" name="price" placeholder="Enter the Price">
  <input type="file" name="image">
  <input type="submit">
</form>
{% endblock %}

demotask7/gadgetsproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Electronic Gadgets Details Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

demotask7/gadgetsproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    Do you want to delete?
    <input type="submit">
</form>

demotask7/gadgetsproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{gadgets.image.url}}" width="250" height="250">
        </div>
        <div class="col-md-6">
            <h2>{{gadgets.title}}</h2>
             <h4>{{gadgets.desc}}</h4>
             <h5>{{gadgets.price}}</h5>

        <a class="btn btn-warning" href="{% url 'gadgetsapp:update' gadgets.id%}">Update</a><br>
        <a class="btn btn-danger" href="{% url 'gadgetsapp:delete' gadgets.id %}">Delete</a>
        </div>
    </div>
</div>


{% endblock %}

demotask7/gadgetsproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

demotask7/gadgetsproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
         {% for i in key1 %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{i.image.url}}" alt="Card image cap" width="250" height="250">
            <div class="card-body">
            <h5 class="card-title">{{i.title}}</h5>
            <p class="card-text">{{i.desc}}</p>
            <a href="{% url 'gadgetsapp:detail' i.id %}" class="btn btn-primary">Show Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}